In [6]:
import numpy as np

In [7]:
nums_list = [1,2,3,4,5]

nums_list

[1, 2, 3, 4, 5]

In [8]:
nums_arr = np.array(nums)

nums_arr

array([1, 2, 3, 4, 5])

In [12]:
double_nums_list = []

for num in nums_list:
    double_nums_list.append(num * 2)
    
display(nums_list)
double_nums_list

[1, 2, 3, 4, 5]


[2, 4, 6, 8, 10]

In [13]:
double_nums_arr = nums_arr * 2

display(nums_arr)
double_nums

array([1, 2, 3, 4, 5])

array([ 2,  4,  6,  8, 10])